### ISSUE TITLE
ngdp install: TypeError: install() got 'dry_run'

### ISSUE THREAD

**Issue by Luashine** [HearthSim/keg#10]
```shell

$ python /usr/local/bin/ngdp install --show-tags tpr/war3 10e02ee17ca62075417a723c1022e7fb
Traceback (most recent call last):
  File "/usr/local/bin/ngdp", line 1102, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: install() got an unexpected keyword argument 'dry_run'
```

Hello! I wanted to download an older Warcraft 3 version from the CDN using keg, it should work, right? I looked up the remotes and versions at (example) [ribbit_data](https://github.com/mdX7/ribbit_data/blob/master/products/w3t/cdn-w3t-127171.bmime) and [ngdp_data](https://github.com/mdX7/ngdp_data/blob/master/US/w3/9900/versions). My goal was to get the files for `1.29.0.8803|10e02ee17ca62075417a723c1022e7fb`.

I suppose there could be a problem with my install, I'm using Cygwin under Windows and the Python's supposed to be executing within the Cygwin environment too. I installed keg with `python -m pip install .` in its directory.

The last three commands resulted in the same error. My command history:

```
cd ngdp-test/
python /usr/local/bin/ngdp init
python /usr/local/bin/ngdp show
python /usr/local/bin/ngdp http://eu.patch.battle.net:1119/
python /usr/local/bin/ngdp remote add http://eu.patch.battle.net:1119/tpr/war3
python /usr/local/bin/ngdp remote add http://eu.patch.battle.net:1119/tpr/war3-live-dev/
python /usr/local/bin/ngdp remote --help
python /usr/local/bin/ngdp remote list
python /usr/local/bin/ngdp install --help
python /usr/local/bin/ngdp install tpr/war3 10e02ee17ca62075417a723c1022e7fb war3-1.29.0.8803 --tags enUS
python /usr/local/bin/ngdp install --tags enUS tpr/war3 10e02ee17ca62075417a723c1022e7fb war3-1.29.0.8803
python /usr/local/bin/ngdp install --show-tags tpr/war3 10e02ee17ca62075417a723c1022e7fb
```

Thanks

**Comment by Pingumania** [comment]
Same problem here on Ubuntu Server and latest python 3.
